def generate_roadmap(gap_report):
    """
    Deterministic roadmap generator
    No LLM required
    Always works
    """

    missing = [
        g["title"]
        for g in gap_report
        if g["coverage"] == "Missing"
    ]

    steps = []

    for i, item in enumerate(missing, 1):
        steps.append(f"{i}. Implement: {item}")

    return "\n".join(steps)


def revise_policy(llm, policy_text, gap_report):
    """
    LLM only rewrites policy
    Roadmap generated by Python (guaranteed)
    """

    missing = [
        g["title"]
        for g in gap_report
        if g["coverage"] == "Missing"
    ]

    prompt = f"""
Rewrite this cybersecurity policy professionally.

Add these missing controls:
{chr(10).join(missing)}

Return ONLY the improved policy text.
"""

    revised = llm.invoke(prompt)

    roadmap = generate_roadmap(gap_report)

    return revised.strip(), roadmap
